### ISSUE TITLE
About a bug

### ISSUE THREAD

**Issue by 123-sweatheart** [om-ai-lab/GroundVLP#1]
While I run the test code. My IDE mentions that "Here is OSError: Can't load the model for '/data9/shz/ckpt/bert-base-uncased'. "  The bug is happens on engine.py 27. Could the author offer the related file? Thanks a lot.

**Comment by juny-park-95** [comment]
it seems hard coded

as you can see, 

https://github.com/om-ai-lab/GroundVLP/blob/f13e9d24947008842c042a2702fbda52c491c0af/models/albef/engine.py#L27

I think we need to convert here into the correct model path.

alternatively,

you can manually clone the models from hugging face.

1. init git lfs
$git lfs install
2. clone the model from hugging face repo.
$git clone https://huggingface.co/bert-base-uncased
3. modify an existing path with cloned path.

```python3
text_encoder='YOUR CLONED BERT PATH'
```

**Comment by Pranomvignesh** [comment]
> you can manually clone the models from hugging face.
init git lfs
$git lfs install
clone the model from hugging face repo.
$git clone https://huggingface.co/bert-base-uncased
modify an existing path with cloned path.

Thanks @juny-park-95 for your solution. This works

**Comment by VoyageWang** [comment]
Hi, I manually download the pre-trained weight of bert-base-uncased. However, when I use the code like
`tokenizer = BertTokenizer.from_pretrained('./bert-base-uncased')`
it will encounter a bug of:
**AttributeError: 'BertTokenizer' object has no attribute 'vocab'**
And I checked that the code doesn't run in the __init__ part of the class class `BertTokenizer(PreTrainedTokenizer):`

I need your help. Thank you so much. I am waiting for your reply.

**Comment by juny-park-95** [comment]
> Hi, I manually download the pre-trained weight of bert-base-uncased. However, when I use the code like `tokenizer = BertTokenizer.from_pretrained('./bert-base-uncased')` it will encounter a bug of: **AttributeError: 'BertTokenizer' object has no attribute 'vocab'** And I checked that the code doesn't run in the **init** part of the class class `BertTokenizer(PreTrainedTokenizer):`
> 
> I need your help. Thank you so much. I am waiting for your reply.

Hi, When you manually downloading, the vocab.txt file or other necessary files may have been missed or the path could have been incorrect. The Python module that uses BertTokenizer has been widely used by others and has been error-verified, so it seems that the issue is not with the code side. As I mentioned earlier, please try downloading the files from the terminal using git lfs. The file size is large, so it may take a few minutes to download. Please be patient.

I hope this resolves your issue.

**Comment by VoyageWang** [comment]
Yes, thanks a lot! I have solved the problem. You do a good job! However, there are some other problem arison. When I try different text queries, I find that some queries make the model malfunction. For example, when I try the query "the little dog has a bandanna around its neck" for following image, it will get the issue like that 
![image](https://github.com/om-ai-lab/GroundVLP/assets/92557104/8cb117dc-d725-4c45-8c7b-a9279149d563)

The issue:
![image](https://github.com/om-ai-lab/GroundVLP/assets/92557104/4651094c-97b8-40c3-b249-adecada63fa4)

It seems that the problem occurs when finding the main words that are used to point to the main objects based on the stanza model. How can I solve it? It also the problem when I test the results of refcoco testB dataset:
COCO_train2014_000000323896.jpg --- silver honda accord
This pair.

I think you also meet, please give me some advice. I am looking forward to your early reply.

**Comment by juny-park-95** [comment]
Well, mentioned problem seems to occur in the following code:

https://github.com/om-ai-lab/GroundVLP/blob/f13e9d24947008842c042a2702fbda52c491c0af/models/albef/engine.py#L202

the all_focus_ids list contains the indices of the important words in the query. (I think) These indices are used to extract information about those words from gradcam.mean(0).

However, the problem arises when some of the index values in all_focus_ids exceed the size of gradcam.mean(0).

For example, if the size of gradcam.mean(0) is 14, but all_focus_ids contains values greater than 14, an IndexError will occur. This is because indices greater than or equal to 14 are not valid indices in gradcam.mean(0).

The reason why all_focus_ids may contain values greater than 14 is related to how the indices are collected and appended to the list.

In the code, all_focus_ids is constructed by extending the indices of the main words obtained from id_map and appending the index 0 (representing the [CLS] token) to the list.

**That means, If the number of tokens in the input text ("the little dog has a bandanna around its neck") is longer than the size of gradcam.mean(0), it is possible that all_focus_ids ends up containing indices that exceed the size of gradcam.mean(0).**

To solve this problem, we need to select only the valid indices from all_focus_ids. In other words, we should use only the indices that do not exceed the size of gradcam.mean(0).

```python3
if find_words:
    valid_focus_ids = [idx for idx in all_focus_ids if idx < gradcam.mean(0).shape[0]]
    if valid_focus_ids:
        gradcam = gradcam.mean(0)[valid_focus_ids, ...].mean(0)
    else:
        gradcam = gradcam.mean(0)[:num_effective_text_token, ...].mean(0)
else:
    gradcam = gradcam.mean(0)[:num_effective_text_token, ...].mean(0)
```

Alternatively, reducing the length of the input text could also be a potential solution.

In modification way, a new list called valid_focus_ids is created to select only the valid indices from all_focus_ids. This way, we can prevent using invalid indices in gradcam.mean(0).

In simple terms, if an index value in all_focus_ids is greater than the size of gradcam.mean(0), it will cause an IndexError. Therefore, it is necessary to modify the code to select and use only the valid indices.

BUT **Reducing the length of the input text could potentially exclude some indices from all_focus_ids, which may lead to poor performance of the model.** This is because important words or tokens associated with those indices might be omitted.

The fixed length of gradcam.mean(0) could indeed be an inherent issue with the model architecture. This length is determined by the design and structure of the model and may be constrained by the size and shape of the input data.

Since modifying the model architecture itself might not be straightforward, selecting only the valid indices from all_focus_ids could be a more practical solution compared to adjusting the length of the input text. By doing so, you can preserve the important indices while conforming to the size limitations of gradcam.mean(0).

Another consideration could be to adapt the input size or architecture of the model. However, this should be approached cautiously as it can have implications on the overall structure and performance of the model.

To address the issue at hand, selecting the valid indices from all_focus_ids seems to be the most appropriate approach. This way, you can ensure compliance with the size limitations of gradcam.mean(0) while retaining as much crucial information as possible.

Additionally, I am not the author or contributor of the code, and I couldn't set up a separate environment to debug the revised code now. I would appreciate your understanding in this regard.

I hope this explanation clarifies the issue for you.

**Comment by juny-park-95** [comment]
> Yes, thanks a lot! I have solved the problem. You do a good job! However, there are some other problem arison. When I try different text queries, I find that some queries make the model malfunction. For example, when I try the query "the little dog has a bandanna around its neck" for following image, it will get the issue like that ![image](https://private-user-images.githubusercontent.com/92557104/314901778-8cb117dc-d725-4c45-8c7b-a9279149d563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzY3NDMsIm5iZiI6MTcxMTAzNjQ0MywicGF0aCI6Ii85MjU1NzEwNC8zMTQ5MDE3NzgtOGNiMTE3ZGMtZDcyNS00YzQ1LThjN2ItYTkyNzkxNDlkNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE1NTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDVlN2EzZGJlNjZjMTZhMGNmYjk3YmEyMjk3YTMwY2Y0NDM2NjdlYmYyYzI5NjhjNWRmNjk4ODc3MmNiYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOM57J5vyOqE_8WXOB2sNntT_J-b1BQoN5mK5IxOI3w)
> 
> The issue: ![image](https://private-user-images.githubusercontent.com/92557104/314902581-4651094c-97b8-40c3-b249-adecada63fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzY3NDMsIm5iZiI6MTcxMTAzNjQ0MywicGF0aCI6Ii85MjU1NzEwNC8zMTQ5MDI1ODEtNDY1MTA5NGMtOTdiOC00MGMzLWIyNDktYWRlY2FkYTYzZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE1NTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmY2MzZWRiZjU2ZDViN2ZlZWUwNzA1YzM2OTdhNzljMTVmZGZjZjNjZjk0MzcxNTNiYjc1ZjRkZWEyMTA3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8x2PcbHfoc5cAsTHpjgKasewfhRmbpz6SPtSmfVikc)
> 
> It seems that the problem occurs when finding the main words that are used to point to the main objects based on the stanza model. How can I solve it? It also the problem when I test the results of refcoco testB dataset: COCO_train2014_000000323896.jpg --- silver honda accord This pair.
> 
> I think you also meet, please give me some advice. I am looking forward to your early reply.

Well, mentioned problem seems to occur in the following code:

https://github.com/om-ai-lab/GroundVLP/blob/f13e9d24947008842c042a2702fbda52c491c0af/models/albef/engine.py#L202

the all_focus_ids list contains the indices of the important words in the query. (I think) These indices are used to extract information about those words from gradcam.mean(0).

However, the problem arises when some of the index values in all_focus_ids exceed the size of gradcam.mean(0).

For example, if the size of gradcam.mean(0) is 14, but all_focus_ids contains values greater than 14, an IndexError will occur. This is because indices greater than 14 are not valid indices in gradcam.mean(0).

The reason why all_focus_ids may contain values greater than 14 is related to how the indices are collected and appended to the list.

In the code, all_focus_ids is constructed by extending the indices of the main words obtained from id_map and appending the index 0 (representing the [CLS] token) to the list.

**That means, If the number of tokens in the input text ("the little dog has a bandanna around its neck") is longer than the size of gradcam.mean(0), it is possible that all_focus_ids ends up containing indices that exceed the size of gradcam.mean(0).**

To solve this problem, we need to select only the valid indices from all_focus_ids. In other words, we should use only the indices that do not exceed the size of gradcam.mean(0).

```python3
if find_words:
    valid_focus_ids = [idx for idx in all_focus_ids if idx < gradcam.mean(0).shape[0]]
    if valid_focus_ids:
        gradcam = gradcam.mean(0)[valid_focus_ids, ...].mean(0)
    else:
        gradcam = gradcam.mean(0)[:num_effective_text_token, ...].mean(0)
else:
    gradcam = gradcam.mean(0)[:num_effective_text_token, ...].mean(0)
```

Alternatively, reducing the length of the input text could also be a potential solution.

In modification way, a new list called valid_focus_ids is created to select only the valid indices from all_focus_ids. This way, we can prevent using invalid indices in gradcam.mean(0).

In simple terms, if an index value in all_focus_ids is greater than the size of gradcam.mean(0), it will cause an IndexError. Therefore, it is necessary to modify the code to select and use only the valid indices.

BUT **Reducing the length of the input text could potentially exclude some indices from all_focus_ids, which may lead to poor performance of the model.** This is because important words or tokens associated with those indices might be omitted.

The fixed length of gradcam.mean(0) could indeed be an inherent issue with the model architecture. This length is determined by the design and structure of the model and may be constrained by the size and shape of the input data.

Since modifying the model architecture itself might not be straightforward, selecting only the valid indices from all_focus_ids could be a more practical solution compared to adjusting the length of the input text. By doing so, you can preserve the important indices while conforming to the size limitations of gradcam.mean(0).

Another consideration could be to adapt the input size or architecture of the model. However, this should be approached cautiously as it can have implications on the overall structure and performance of the model.

To address the issue at hand, selecting the valid indices from all_focus_ids seems to be the most appropriate approach. This way, you can ensure compliance with the size limitations of gradcam.mean(0) while retaining as much crucial information as possible.

Additionally, I am not the author or contributor of the code, and I couldn't set up a separate environment to debug the revised code now. I would appreciate your understanding in this regard.

I hope this explanation clarifies the issue for you.
